#jpeg(file="Exports_annual_bxp.jpg",width=480,height=480)
quartz(width=9,height=9,dpi=72)
boxplot(log(results.7[,17:19]),names=c("2008","2009","2010"),main="연도별 수출", ylab="log(수출)")
#dev.off()
#library(lattice)
#jpeg(file="RnD_annual_hist.jpg",width=480,height=480)
#histogram(~Input08+Input09+Input10,data=RnD, layout=c(1,3), xlab="Budget spent", main="Annual R&D Budget", strip=strip.custom(factor.levels=c("2008","2009","2010")))
#dev.off()
#jpeg(file="Exports_by_grade_bxp.jpg",width=640,height=640)
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2,byrow=T))
layout.show(4)
boxplot(log(export08)~grade,data=results.7, main="인센티브 등급별 수출",sub="2008",ylab="log(수출)")
boxplot(log(export09)~grade,data=results.7, main="인센티브 등급별 수출",sub="2009",ylab="log(수출)")
boxplot(log(export10)~grade,data=results.7, main="인센티브 등급별 수출",sub="2010",ylab="log(수출)")
boxplot(log(export.total)~grade,data=results.7, main="인센티브 등급별 수출",sub="08~10",ylab="log(수출)")
#dev.off()
#jpeg(file="Exports_by_Region_bxp.jpg",width=640,height=640)
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2,byrow=T))
layout.show(4)
boxplot(log(export08)~Region,data=results.7, main="권역별 수출",sub="2008", names=c("영남", "중부", "호남"),ylab="log(수출)")
boxplot(log(export09)~Region,data=results.7, main="권역별 수출",sub="2009", names=c("영남", "중부", "호남"),ylab="log(수출)")
boxplot(log(export10)~Region,data=results.7, main="권역별 수출",sub="2010", names=c("영남", "중부", "호남"),ylab="log(수출)")
boxplot(log(export.total)~Region,data=results.7, main="권역별 수출",sub="08~10", names=c("영남", "중부", "호남"),ylab="log(수출)")
#dev.off()