#jpeg(file="RnD_annual_bxp.jpg",width=480,height=480)
#quartz(width=9,height=9,dpi=72)
#boxplot(RnD[,c(3,5,7)],names=c("2008","2009","2010"),main="연차별 실적")
#dev.off()
#library(lattice)
#jpeg(file="RnD_annual_hist.jpg",width=480,height=480)
#quartz(width=9,height=9,dpi=72)
#histogram(~Input08+Input09+Input10,data=RnD, layout=c(1,3), xlab="R&D budget spent", main="Annual R&D Budget", strip=strip.custom(factor.levels=c("2008","2009","2010")))
#dev.off()
#jpeg(file="RnD_by_grade_bxp.jpg",width=640,height=640)
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2,byrow=T))
layout.show(4)
boxplot(budget$PM08~results.7$grade, main="인센티브 등급과 홍보마케팅 예산 집행실적",sub="2008")
boxplot(budget$PM09~results.7$grade, main="인센티브 등급과 홍보마케팅 예산 집행실적",sub="2009")
boxplot(budget$PM10~results.7$grade, main="인센티브 등급과 홍보마케팅 예산 집행실적",sub="2010")
boxplot(budget$PM08+budget$PM09+budget$PM10~results.7$grade, main="인센티브 등급과 홍보마케팅 예산 집행실적",sub="08~10")
#dev.off()
#jpeg(file="RnD_by_Region_bxp.jpg",width=640,height=640)
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2,byrow=T))
layout.show(4)
boxplot(budget$PM08~results.7$Region, main="권역별 홍보마케팅 예산 집행실적",sub="2008", names=c("영남", "중부", "호남"))
boxplot(budget$PM09~results.7$Region, main="권역별 홍보마케팅 예산 집행실적",sub="2009", names=c("영남", "중부", "호남"))
boxplot(budget$PM10~results.7$Region, main="권역별 홍보마케팅 예산 집행실적",sub="2010", names=c("영남", "중부", "호남"))
boxplot(budget$PM08+budget$PM09+budget$PM10~results.7$Region, main="권역별 홍보마케팅 예산 집행실적",sub="08~10", names=c("영남", "중부", "호남"))
#dev.off()