#jpeg(file="RnD_annual_bxp.jpg",width=480,height=480)
#boxplot(RnD[,c(3,5,7)],names=c("2008","2009","2010"),main="Achievements Each Year")
#dev.off()
#library(lattice)
#jpeg(file="RnD_annual_hist.jpg",width=480,height=480)
#histogram(~Input08+Input09+Input10,data=RnD, layout=c(1,3), xlab="Budget spent", main="Annual R&D Budget", strip=strip.custom(factor.levels=c("2008","2009","2010")))
#dev.off()
#jpeg(file="RnD_by_grade_bxp.jpg",width=640,height=640)
#layout(matrix(1:4,nrow=2,byrow=T))
#layout.show(4)
#boxplot(Output08~results.7$grade,data=RnD, main="Achievements by Incentive Grade",sub="2008")
#boxplot(Output09~results.7$grade,data=RnD, main="Achievements by Incentive Grade",sub="2009")
#boxplot(Output10~results.7$grade,data=RnD, main="Achievements by Incentive Grade",sub="2010")
#boxplot(Output.total~results.7$grade,data=RnD, main="Achievements by Incentive Grade",sub="08~10")
#dev.off()
jpeg(file="RnD_by_Region_bxp.jpg",width=640,height=640)
layout(matrix(1:4,nrow=2,byrow=T))
layout.show(4)
#boxplot(Output08~results.7$Region,data=RnD, main="Achievements by Region",sub="2008")
#boxplot(Output09~results.7$Region,data=RnD, main="Achievements by Region",sub="2009")
#boxplot(Output10~results.7$Region,data=RnD, main="Achievements by Region",sub="2010")
#boxplot(Output.total~results.7$Region,data=RnD, main="Achievements by Region",sub="08~10")
boxplot(Output08~results.7$Region,data=RnD, main="Achievements by Region",sub="2008", names=c("Youngnam","Middle","Honam"))
boxplot(Output09~results.7$Region,data=RnD, main="Achievements by Region",sub="2009",names=c("Youngnam","Middle","Honam"))
boxplot(Output10~results.7$Region,data=RnD, main="Achievements by Region",sub="2010",names=c("Youngnam","Middle","Honam"))
boxplot(Output.total~results.7$Region,data=RnD, main="Achievements by Region",sub="08~10",names=c("Youngnam","Middle","Honam"))
dev.off()