#jpeg(file="RnD_budget_vs_results_kr.jpg",width=640,height=640)
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2, byrow=T))
layout.show(4)
plot(budget$PP08,log(results.7$sales08),xlab="생산 및 가공 예산 집행액", ylab="log(농어촌기업 매출)", main="2008")
plot(budget$PP09,log(results.7$sales09),xlab="생산 및 가공 예산 집행액", ylab="log(농어촌기업 매출)", main="2009")
plot(budget$PP10,log(results.7$sales10),xlab="생산 및 가공 예산 집행액", ylab="log(농어촌기업 매출)", main="2010")
plot(budget$PP08+budget$PP09+budget$PP10,log(results.7$sales.total),xlab="생산 및 가공 예산 집행액", ylab="log(농어촌기업 매출)", main="08~10")
#dev.off()
quartz(width=9,height=9,dpi=72)
layout(matrix(1:4,nrow=2, byrow=T))
layout.show(4)
plot(budget$PM08,log(results.7$sales08),xlab="홍보 및 마케팅 예산 집행액", ylab="log(농어촌기업 매출)", main="2008")
plot(budget$PM09,log(results.7$sales09),xlab="홍보 및 마케팅 예산 집행액", ylab="log(농어촌기업 매출)", main="2009")
plot(budget$PM10,log(results.7$sales10),xlab="홍보 및 마케팅 예산 집행액", ylab="log(농어촌기업 매출)", main="2010")
plot(budget$PM08+budget$PM09+budget$PM10,log(results.7$sales.total),xlab="홍보 및 마케팅 예산 집행액", ylab="log(농어촌기업 매출)", main="08~10")
#quartz(width=9,height=9,dpi=72)
#layout(matrix(1:4,nrow=2, byrow=T))
#layout.show(4)
#plot(budget$RD08,log(results.7$sales08),xlab="연구개발 예산 집행액", ylab="log(농어촌기업 매출)", main="2008")
#plot(budget$RD09,log(results.7$sales09),xlab="연구개발 예산 집행액", ylab="log(농어촌기업 매출)", main="2009")
#plot(budget$RD10,log(results.7$sales10),xlab="연구개발 예산 집행액", ylab="log(농어촌기업 매출)", main="2010")
#plot(budget$RD08+budget$RD09+budget$RD10,log(results.7$sales.total),xlab="연구개발 예산 집행액", ylab="log(농어촌기업 매출)", main="08~10")
